name = "growman-web"
main = ".open-next/worker.js"

compatibility_date = "2025-12-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "growman.live"
custom_domain = true

[observability]
[observability.logs]
enabled = true

head_sampling_rate = 1
invocation_logs = true
persist = true