import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
// import Navbar from "@repo/ui/navbar";
import Navbar from "../components/hompage/navbar";
import { ToastContainer } from "../lib/toast";

// import { SessionProvider } from "next-auth/react";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geist.className} bg-linear-to-r from-green-50 to-emerald-50`}
      >
        <div className="z-100">
          <Navbar />
        </div>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
