{
 "title": "API Performance Dashboard",
 "description": "Get information for api performance",
 "tags": [
  "api",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top 10 Slowest APIs (Avg Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10,(\n  sum by (uri, method, app) (\n    rate(http_server_requests_seconds_sum{status=~\"2..\"}[$__range])\n  )\n  /\n  sum by (uri, method, app) (\n    rate(http_server_requests_seconds_count{status=~\"2..\"}[$__range])\n  )\n))"
    }
   ]
  },
  {
   "title": "Top 5 Busiest APIs (RPS)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (app, uri, method) (rate(http_server_requests_seconds_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests (Max Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max by (path) (max_over_time(http_request_duration_seconds_max{method!=\"\", path!=\"\", service!=\"\", status=~\"2..\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "Total RPS"
    }
   ]
  }
 ]
}